### ISSUE TITLE
error when deleting non movie files

### ISSUE THREAD

**Issue by jinjorge** [tkdan235/mediatidy#2]
received an error when deleting non movie files with the latest version of mediated(via npm)

```
mediatidy: Delete all files that are not video types?:  (no) yes

/usr/local/lib/node_modules/mediatidy/lib/media.coffee:321
                    throw err;
                          ^
Error: EACCES, unlink '/Volumes/Movies/.12 Years A Slave (2013).mkv.qhQUxg'


media:mediatidy mediaserver$ 
```

**Comment by tkdan235** [comment]
I renamed a file to that file name and it seemed to work for me:

```
==> delete files which are not video types
DELETE(?): /Users/daniel/Pictures/test/.12 Years A Slave (2013).mkv.qhQUxg
mediatidy: Delete all files that are not video types?:  (no) yes
DELETED: /Users/daniel/Pictures/test/.12 Years A Slave (2013).mkv.qhQUxg
files deleted and removed from database...
```

Can you run `ls -al` in that directory and show me the results for that file?

**Comment by jinjorge** [comment]
Ok, will do

**Comment by jinjorge** [comment]
requested ls -al output

https://gist.github.com/jinjorge/f4ced83e5c8f975aadb8

**Comment by tkdan235** [comment]
It appears the files only have sudo execute/read/write... for instance:

```-rwx------  1 mediaserver  staff         4096 Nov 21 23:35 ._.DS_Store```

Try `rm ._.DS_Store` when you get a chance.  If that doesn't work, definitely a permission issue.

Here is an example of my an item from my library:

```-rwxrwxrwx   1 daniel  staff   3028618146 Jun 23  2014 lolwut (2012).mkv```

**Comment by jinjorge** [comment]
@tkdan235 I was able to successfully remove that file without sudo access

```
media:Movies mediaserver$ rm /Volumes/Movies/._.DS_Store
media:Movies mediaserver$ ls -al
```

**Comment by jinjorge** [comment]
updated the app and run mediatidy update, went through and cleaned up my library. After the update completed, I run the update cmd again

```
DELETE(?): /Volumes/Movies/.12 Years A Slave (2013).mkv.qhQUxg
DELETE(?): /Volumes/Movies/.AppleDB/__db.001
DELETE(?): /Volumes/Movies/.AppleDB/__db.002
DELETE(?): /Volumes/Movies/.AppleDB/__db.003
DELETE(?): /Volumes/Movies/.AppleDB/__db.004
DELETE(?): /Volumes/Movies/.AppleDB/__db.005
DELETE(?): /Volumes/Movies/.AppleDB/__db.006
DELETE(?): /Volumes/Movies/.AppleDB/cnid2.db
DELETE(?): /Volumes/Movies/.AppleDB/db_errlog
DELETE(?): /Volumes/Movies/.AppleDB/lock
DELETE(?): /Volumes/Movies/.AppleDB/log.0000000002
DELETE(?): /Volumes/Movies/.AppleDB/log.0000000003
mediatidy: Delete all files that are not video types?:  (no) yes
DELETED: /Volumes/Movies/.12 Years A Slave (2013).mkv.qhQUxg
DELETED: /Volumes/Movies/.AppleDB/__db.001
```

Finally able to delete the file that was causing a problem. you can close this issue.

Thanks for all the help!!
