### ISSUE TITLE
unable to add new paths

### ISSUE THREAD

**Issue by jinjorge** [tkdan235/mediatidy#5]
Run mediatidy in the past with only one folder path /Volumes/Movies. Today, run the command to add a path and got the following

```
media:mediatidy mediaserver$ mediatidy paths add
==> update paths to media files for mediatidy to tidy up!
==> remove all media paths from mediatidy
CURRENT PATH: /Volumes/Movies
mediatidy: Add another media path to mediatidy?:  (no) CURRENT PATH: /Volumes/Movies
mediatidy: Delete all paths from mediatidy?:  (no) 
```
Notice that the answer to "Add another media path to mediatidy" is answered with the folder path that's currently configured.

Also the questions are reversed - as in wouldn't it make sense to ask to delete all paths before asking to add new folder paths? (Would you like me to open a different issue for this)

Thanks!

**Comment by tkdan235** [comment]
should be fixed...  good catch!  whoops!
